version: '2.0'
services:
  nginx:
    image: nginx:1.21.3
    ports: 
      - 443:443
    volumes: 
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./opt/secrets:/app/certs
      - ./opt/logs/nginx:/app/api/logs
    networks:
      - machete-bridge      
  dotnet:
    env_file: "./env_variables.conf"
    build: .
    ports:
      - 4213:4213
    volumes:
      - .:/code
      - ./opt/logs/dotnet:/var/log
    networks:
      - machete-bridge
  sqlserver:
    env_file: "./env_variables.conf"
    environment:
      ACCEPT_EULA: Y
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    networks:
      - machete-bridge

networks:
  machete-bridge:
    driver: bridge