version: '3'

networks:
  machete:
    driver: bridge
services:
  nginx:
    image: nginx:1.21.3
    ports:
      - 443:443
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./opt/secrets:/app/certs
      - ./opt/logs/nginx:/app/api/logs

  dotnet:
    env_file: "./env_variables.conf"
    build: .
    ports:
      - 4213:4213
    volumes:
      - .:/code
      - ./opt/logs/dotnet:/var/log
      - ./appsettings.json:/app/api/appsettings.json

  sqlserver:
    env_file: "./env_variables.conf"
    environment:
      ACCEPT_EULA: Y
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
  postgres:
    image: postgres:9.6-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      machete:
        aliases:
          - "postgres"
    volumes:
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/init.sql

  keycloak:
    image: quay.io/keycloak/keycloak:nightly
    ports:
      - 0.0.0.0:8100:8100
      - 0.0.0.0:8101:8101
    env_file: "./env_variables.conf"
    command: ["start-dev --auto-build --http-port=8100 --https-port=8101 --log-level=DEBUG --db=postgres --features=token-exchange --db-url=jdbc:postgresql://postgres:5432/keycloak --db-username=postgres --db-password=postgres --import-realm"]
    volumes:
      - './keycloak-test-realm.json:/opt/keycloak/data/import/keycloak-test-realm.json'
    networks:
      machete:
        aliases:
          - "keycloak"
    depends_on:
      - postgres