// <auto-generated />
namespace Machete.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class BusinessName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BusinessName));
        
        string IMigrationMetadata.Id
        {
            get { return "201404020143565_BusinessName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
