// <auto-generated />
namespace Machete.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class activity_lookup_strings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(activity_lookup_strings));
        
        string IMigrationMetadata.Id
        {
            get { return "201612270623502_activity_lookup_strings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
