// <auto-generated />
namespace Machete.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Identity_upgrade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Identity_upgrade));
        
        string IMigrationMetadata.Id
        {
            get { return "201611211803005_Identity_upgrade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
