// <auto-generated />
namespace Machete.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v1_13_1replace_paypal_fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1_13_1replace_paypal_fields));
        
        string IMigrationMetadata.Id
        {
            get { return "201712232240329_v1_13_1-replace_paypal_fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
