// <auto-generated />
namespace Machete.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v1_13_3Transport_Provider_Availability : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1_13_3Transport_Provider_Availability));
        
        string IMigrationMetadata.Id
        {
            get { return "201805140450212_v1_13_3-Transport_Provider_Availability"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
