version: '3.7'

services:
    cmdline-dev:
      build:
          context: .
      working_dir: /app
      volumes:
        - "..:/app"
      command: "sleep infinity"

    sqlserver_dev:
      env_file: "../env_variables.conf"
      environment:
        ACCEPT_EULA: Y
      image: mcr.microsoft.com/mssql/server
      ports:
        - 1433:1433

