//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machete.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Persons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Persons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Machete.Web.Resources.Persons", typeof(Persons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string allf {
            get {
                return ResourceManager.GetString("allf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string basicinfo {
            get {
                return ResourceManager.GetString("basicinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string boxlegend {
            get {
                return ResourceManager.GetString("boxlegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the buttons to the left to sort the table below..
        /// </summary>
        public static string clicksort {
            get {
                return ResourceManager.GetString("clicksort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string createClear {
            get {
                return ResourceManager.GetString("createClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Person.
        /// </summary>
        public static string createlink {
            get {
                return ResourceManager.GetString("createlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string createsubmit {
            get {
                return ResourceManager.GetString("createsubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to person::create.
        /// </summary>
        public static string createtitle {
            get {
                return ResourceManager.GetString("createtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Worker.
        /// </summary>
        public static string createworker {
            get {
                return ResourceManager.GetString("createworker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this person? All information will be deleted, forever. If you want to de-activate this Person, cancel from this dialog and uncheck the &apos;active&apos; box on the person page..
        /// </summary>
        public static string deleteconfirmation {
            get {
                return ResourceManager.GetString("deleteconfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deletelink {
            get {
                return ResourceManager.GetString("deletelink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deletesubmit {
            get {
                return ResourceManager.GetString("deletesubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to person::delete.
        /// </summary>
        public static string deletetitle {
            get {
                return ResourceManager.GetString("deletetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string editlink {
            get {
                return ResourceManager.GetString("editlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Person.
        /// </summary>
        public static string editpersonlink {
            get {
                return ResourceManager.GetString("editpersonlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string editsubmit {
            get {
                return ResourceManager.GetString("editsubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to person::edit.
        /// </summary>
        public static string edittitle {
            get {
                return ResourceManager.GetString("edittitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string expired {
            get {
                return ResourceManager.GetString("expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to List of Persons.
        /// </summary>
        public static string indexreturnlink {
            get {
                return ResourceManager.GetString("indexreturnlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to person::index.
        /// </summary>
        public static string indextitle {
            get {
                return ResourceManager.GetString("indextitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List persons.
        /// </summary>
        public static string listlink {
            get {
                return ResourceManager.GetString("listlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanctioned/Expelled.
        /// </summary>
        public static string sancExp {
            get {
                return ResourceManager.GetString("sancExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string viewlink {
            get {
                return ResourceManager.GetString("viewlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to person::view.
        /// </summary>
        public static string viewtitle {
            get {
                return ResourceManager.GetString("viewtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker information.
        /// </summary>
        public static string workerinfo {
            get {
                return ResourceManager.GetString("workerinfo", resourceCulture);
            }
        }
    }
}
