//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machete.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Reports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Machete.Web.Resources.Reports", typeof(Reports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string activitiesTab {
            get {
                return ResourceManager.GetString("activitiesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string avgIncome {
            get {
                return ResourceManager.GetString("avgIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DWC Dispatched.
        /// </summary>
        public static string dwcDispatch {
            get {
                return ResourceManager.GetString("dwcDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DWC Signins.
        /// </summary>
        public static string dwcSignins {
            get {
                return ResourceManager.GetString("dwcSignins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HHH Dispatched.
        /// </summary>
        public static string hhhDispatch {
            get {
                return ResourceManager.GetString("hhhDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HHH Signins.
        /// </summary>
        public static string hhhSignins {
            get {
                return ResourceManager.GetString("hhhSignins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Orders.
        /// </summary>
        public static string ordersTab {
            get {
                return ResourceManager.GetString("ordersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machete Summary Reports.
        /// </summary>
        public static string summaryHeader {
            get {
                return ResourceManager.GetString("summaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the menus below to select different types of summary reports. Use the buttons at the top of the report to toggle the display..
        /// </summary>
        public static string summaryInstructions {
            get {
                return ResourceManager.GetString("summaryInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summaries.
        /// </summary>
        public static string summaryTab {
            get {
                return ResourceManager.GetString("summaryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hours.
        /// </summary>
        public static string totalHours {
            get {
                return ResourceManager.GetString("totalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Income.
        /// </summary>
        public static string totalIncome {
            get {
                return ResourceManager.GetString("totalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Signins.
        /// </summary>
        public static string totalSignins {
            get {
                return ResourceManager.GetString("totalSignins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers.
        /// </summary>
        public static string workersTab {
            get {
                return ResourceManager.GetString("workersTab", resourceCulture);
            }
        }
    }
}
