//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machete.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Reports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Machete.Web.Resources.Reports", typeof(Reports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string activeMembers {
            get {
                return ResourceManager.GetString("activeMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities Reports.
        /// </summary>
        public static string activitiesHeader {
            get {
                return ResourceManager.GetString("activitiesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string activitiesTab {
            get {
                return ResourceManager.GetString("activitiesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the menu items below to select different types of activity reports. Use the buttons at the top of the report to toggle the display. For daily Activities information, see the summary on the Activity tab..
        /// </summary>
        public static string activityInstructions {
            get {
                return ResourceManager.GetString("activityInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gardening 2.
        /// </summary>
        public static string advGarden {
            get {
                return ResourceManager.GetString("advGarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string avgIncome {
            get {
                return ResourceManager.GetString("avgIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gardening 1.
        /// </summary>
        public static string basicGarden {
            get {
                return ResourceManager.GetString("basicGarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string cancelledJobs {
            get {
                return ResourceManager.GetString("cancelledJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a day to see results..
        /// </summary>
        public static string dayInstructions {
            get {
                return ResourceManager.GetString("dayInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatched.
        /// </summary>
        public static string dispatched {
            get {
                return ResourceManager.GetString("dispatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labor Dispatch.
        /// </summary>
        public static string dwcDispatch {
            get {
                return ResourceManager.GetString("dwcDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labor Pending.
        /// </summary>
        public static string dwcFuture {
            get {
                return ResourceManager.GetString("dwcFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labor.
        /// </summary>
        public static string dwcList {
            get {
                return ResourceManager.GetString("dwcList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Requested).
        /// </summary>
        public static string dwcPropio {
            get {
                return ResourceManager.GetString("dwcPropio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labor Req. Fut..
        /// </summary>
        public static string dwcPropioFuture {
            get {
                return ResourceManager.GetString("dwcPropioFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labor Signins.
        /// </summary>
        public static string dwcSignins {
            get {
                return ResourceManager.GetString("dwcSignins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Jobs.
        /// </summary>
        public static string empJobs {
            get {
                return ResourceManager.GetString("empJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Reports.
        /// </summary>
        public static string employersHeader {
            get {
                return ResourceManager.GetString("employersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the menus below to select different types of employer reports. Use the buttons at the top of the reports to toggle the display..
        /// </summary>
        public static string employersInstructions {
            get {
                return ResourceManager.GetString("employersInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employers.
        /// </summary>
        public static string employersTab {
            get {
                return ResourceManager.GetString("employersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Zip Codes.
        /// </summary>
        public static string empZipCodes {
            get {
                return ResourceManager.GetString("empZipCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESL(&gt; 12 h.).
        /// </summary>
        public static string eslAssessed {
            get {
                return ResourceManager.GetString("eslAssessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Family (running total).
        /// </summary>
        public static string familyHouseholds {
            get {
                return ResourceManager.GetString("familyHouseholds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Ed..
        /// </summary>
        public static string finEd {
            get {
                return ResourceManager.GetString("finEd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Future.
        /// </summary>
        public static string futureTotal {
            get {
                return ResourceManager.GetString("futureTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic Dispatched.
        /// </summary>
        public static string hhhDispatch {
            get {
                return ResourceManager.GetString("hhhDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic Future.
        /// </summary>
        public static string hhhFuture {
            get {
                return ResourceManager.GetString("hhhFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic.
        /// </summary>
        public static string hhhList {
            get {
                return ResourceManager.GetString("hhhList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Requested).
        /// </summary>
        public static string hhhPropio {
            get {
                return ResourceManager.GetString("hhhPropio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic Req. Future.
        /// </summary>
        public static string hhhPropioFuture {
            get {
                return ResourceManager.GetString("hhhPropioFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic Signins.
        /// </summary>
        public static string hhhSignins {
            get {
                return ResourceManager.GetString("hhhSignins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay, Got It.
        /// </summary>
        public static string hideHelp {
            get {
                return ResourceManager.GetString("hideHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select any day in a month to see results for that month..
        /// </summary>
        public static string monthInstructions {
            get {
                return ResourceManager.GetString("monthInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Family (new).
        /// </summary>
        public static string newFamilyHousholds {
            get {
                return ResourceManager.GetString("newFamilyHousholds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singles (new).
        /// </summary>
        public static string newSingleAdults {
            get {
                return ResourceManager.GetString("newSingleAdults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of jobs.
        /// </summary>
        public static string noWeekJobs {
            get {
                return ResourceManager.GetString("noWeekJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machete Work Order Reports.
        /// </summary>
        public static string ordersHeader {
            get {
                return ResourceManager.GetString("ordersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the menus below to select different types of reports about work orders. Use the buttons at the top of the reports to toggle the display..
        /// </summary>
        public static string ordersInstructions {
            get {
                return ResourceManager.GetString("ordersInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Orders.
        /// </summary>
        public static string ordersTab {
            get {
                return ResourceManager.GetString("ordersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSHA.
        /// </summary>
        public static string osha {
            get {
                return ResourceManager.GetString("osha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety.
        /// </summary>
        public static string safetyTraining {
            get {
                return ResourceManager.GetString("safetyTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singles (running total).
        /// </summary>
        public static string singleAdults {
            get {
                return ResourceManager.GetString("singleAdults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string skillsTraining {
            get {
                return ResourceManager.GetString("skillsTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSRS.
        /// </summary>
        public static string ssrsTab {
            get {
                return ResourceManager.GetString("ssrsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Summary Reports.
        /// </summary>
        public static string summaryHeader {
            get {
                return ResourceManager.GetString("summaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the menus below to select different types of summary reports. Use the buttons at the top of the report to toggle the display..
        /// </summary>
        public static string summaryInstructions {
            get {
                return ResourceManager.GetString("summaryInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Summaries.
        /// </summary>
        public static string summaryTab {
            get {
                return ResourceManager.GetString("summaryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary.
        /// </summary>
        public static string tempJobs {
            get {
                return ResourceManager.GetString("tempJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        public static string totalAssignments {
            get {
                return ResourceManager.GetString("totalAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hours.
        /// </summary>
        public static string totalHours {
            get {
                return ResourceManager.GetString("totalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Income.
        /// </summary>
        public static string totalIncome {
            get {
                return ResourceManager.GetString("totalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signins.
        /// </summary>
        public static string totalSignins {
            get {
                return ResourceManager.GetString("totalSignins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique.
        /// </summary>
        public static string unique {
            get {
                return ResourceManager.GetString("unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique.
        /// </summary>
        public static string uniqueSignins {
            get {
                return ResourceManager.GetString("uniqueSignins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekday.
        /// </summary>
        public static string weekday {
            get {
                return ResourceManager.GetString("weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours of work.
        /// </summary>
        public static string weekEstDailyHours {
            get {
                return ResourceManager.GetString("weekEstDailyHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est. Income.
        /// </summary>
        public static string weekEstPayment {
            get {
                return ResourceManager.GetString("weekEstPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Hourly.
        /// </summary>
        public static string weekHourlyWage {
            get {
                return ResourceManager.GetString("weekHourlyWage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a day to see results for that week..
        /// </summary>
        public static string weekInstructions {
            get {
                return ResourceManager.GetString("weekInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top req. skills.
        /// </summary>
        public static string weekJobsSect {
            get {
                return ResourceManager.GetString("weekJobsSect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Went To Class.
        /// </summary>
        public static string wentToClass {
            get {
                return ResourceManager.GetString("wentToClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Reports.
        /// </summary>
        public static string workersHeader {
            get {
                return ResourceManager.GetString("workersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the menus below to select different types of reports about workers. Use the buttons at the top of the reports to toggle the display..
        /// </summary>
        public static string workersInstructions {
            get {
                return ResourceManager.GetString("workersInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers.
        /// </summary>
        public static string workersTab {
            get {
                return ResourceManager.GetString("workersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select any day in a year to see the results of a fiscal year ending on that day..
        /// </summary>
        public static string yearInstructions {
            get {
                return ResourceManager.GetString("yearInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string zip {
            get {
                return ResourceManager.GetString("zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +4.
        /// </summary>
        public static string zipplusfour {
            get {
                return ResourceManager.GetString("zipplusfour", resourceCulture);
            }
        }
    }
}
