//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machete.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkOrders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkOrders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Machete.Web.Resources.WorkOrders", typeof(WorkOrders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate order.
        /// </summary>
        public static string activatesubmit {
            get {
                return ResourceManager.GetString("activatesubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active assignment.
        /// </summary>
        public static string activeassignment {
            get {
                return ResourceManager.GetString("activeassignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active order.
        /// </summary>
        public static string activeorder {
            get {
                return ResourceManager.GetString("activeorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment count.
        /// </summary>
        public static string assigncount {
            get {
                return ResourceManager.GetString("assigncount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact person:.
        /// </summary>
        public static string boxcontactname {
            get {
                return ResourceManager.GetString("boxcontactname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on:.
        /// </summary>
        public static string boxdatecreated {
            get {
                return ResourceManager.GetString("boxdatecreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order.
        /// </summary>
        public static string boxlegend {
            get {
                return ResourceManager.GetString("boxlegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string btnActive {
            get {
                return ResourceManager.GetString("btnActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string btnAll {
            get {
                return ResourceManager.GetString("btnAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string btnCancelled {
            get {
                return ResourceManager.GetString("btnCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string btnCompleted {
            get {
                return ResourceManager.GetString("btnCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string btnExpired {
            get {
                return ResourceManager.GetString("btnExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string btnOnline {
            get {
                return ResourceManager.GetString("btnOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string btnPending {
            get {
                return ResourceManager.GetString("btnPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled assignment.
        /// </summary>
        public static string cancelledassignment {
            get {
                return ResourceManager.GetString("cancelledassignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled order.
        /// </summary>
        public static string cancelledorder {
            get {
                return ResourceManager.GetString("cancelledorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Employer.
        /// </summary>
        public static string changeemployer {
            get {
                return ResourceManager.GetString("changeemployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete active &amp; assigned orders.
        /// </summary>
        public static string completeactiveassigned {
            get {
                return ResourceManager.GetString("completeactiveassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed assignment.
        /// </summary>
        public static string completedassignment {
            get {
                return ResourceManager.GetString("completedassignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed order.
        /// </summary>
        public static string completedorder {
            get {
                return ResourceManager.GetString("completedorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy employer info.
        /// </summary>
        public static string copyemployerinfo {
            get {
                return ResourceManager.GetString("copyemployerinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Work Order.
        /// </summary>
        public static string createlink {
            get {
                return ResourceManager.GetString("createlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create a new work order, you must first select an existing employer record or create a new employer. Click on the menu box (above) to create or select an employer. Alternatively, you can view an existing work order (below) and then view all orders for that employer..
        /// </summary>
        public static string createnolinkmsg {
            get {
                return ResourceManager.GetString("createnolinkmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string createsubmit {
            get {
                return ResourceManager.GetString("createsubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workorder::create.
        /// </summary>
        public static string createtitle {
            get {
                return ResourceManager.GetString("createtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date needed:.
        /// </summary>
        public static string dateneeded {
            get {
                return ResourceManager.GetString("dateneeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this work order? All information will be deleted, forever. If you want to de-activate this work order, cancel from this dialog and uncheck the &apos;active&apos; box on the work order page..
        /// </summary>
        public static string deleteconfirmation {
            get {
                return ResourceManager.GetString("deleteconfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete .
        /// </summary>
        public static string deletelink {
            get {
                return ResourceManager.GetString("deletelink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deletesubmit {
            get {
                return ResourceManager.GetString("deletesubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workorder::delete.
        /// </summary>
        public static string deletetitle {
            get {
                return ResourceManager.GetString("deletetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string editcancel {
            get {
                return ResourceManager.GetString("editcancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit .
        /// </summary>
        public static string editlink {
            get {
                return ResourceManager.GetString("editlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string editsubmit {
            get {
                return ResourceManager.GetString("editsubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workorder::edit.
        /// </summary>
        public static string edittitle {
            get {
                return ResourceManager.GetString("edittitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit work order.
        /// </summary>
        public static string editworkorderlink {
            get {
                return ResourceManager.GetString("editworkorderlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to move this work order? The tab will be saved and closed. To open it, you must go to the Employer list tab and find the new employer containing the work order..
        /// </summary>
        public static string empChgConfirm {
            get {
                return ResourceManager.GetString("empChgConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string empChgConfirmSubmit {
            get {
                return ResourceManager.GetString("empChgConfirmSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a new employer.
        /// </summary>
        public static string empChgConfirmTitle {
            get {
                return ResourceManager.GetString("empChgConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired assignment.
        /// </summary>
        public static string expiredassignment {
            get {
                return ResourceManager.GetString("expiredassignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired order.
        /// </summary>
        public static string expiredorder {
            get {
                return ResourceManager.GetString("expiredorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Flexible).
        /// </summary>
        public static string flexible {
            get {
                return ResourceManager.GetString("flexible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active orders with fulfilled worker assignments for the date you selected..
        /// </summary>
        public static string groupviewerror {
            get {
                return ResourceManager.GetString("groupviewerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string hirerAccount {
            get {
                return ResourceManager.GetString("hirerAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire a Worker.
        /// </summary>
        public static string hireWorker {
            get {
                return ResourceManager.GetString("hireWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to list of work orders.
        /// </summary>
        public static string indexreturnlink {
            get {
                return ResourceManager.GetString("indexreturnlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workorder::index.
        /// </summary>
        public static string indextitle {
            get {
                return ResourceManager.GetString("indextitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Work Orders.
        /// </summary>
        public static string listlink {
            get {
                return ResourceManager.GetString("listlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of ALL work orders.
        /// </summary>
        public static string listlinkall {
            get {
                return ResourceManager.GetString("listlinkall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of positions.
        /// </summary>
        public static string listOfPositions {
            get {
                return ResourceManager.GetString("listOfPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google map.
        /// </summary>
        public static string mapbutton {
            get {
                return ResourceManager.GetString("mapbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online source?.
        /// </summary>
        public static string onlineSource {
            get {
                return ResourceManager.GetString("onlineSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending assignment.
        /// </summary>
        public static string pendingassignment {
            get {
                return ResourceManager.GetString("pendingassignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending order.
        /// </summary>
        public static string pendingorder {
            get {
                return ResourceManager.GetString("pendingorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print active orders.
        /// </summary>
        public static string printactive {
            get {
                return ResourceManager.GetString("printactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print active &amp; assigned orders.
        /// </summary>
        public static string printactiveassigned {
            get {
                return ResourceManager.GetString("printactiveassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print order.
        /// </summary>
        public static string printlink {
            get {
                return ResourceManager.GetString("printlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print work order.
        /// </summary>
        public static string printWorkOrder {
            get {
                return ResourceManager.GetString("printWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (sharp).
        /// </summary>
        public static string sharp {
            get {
                return ResourceManager.GetString("sharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string summary {
            get {
                return ResourceManager.GetString("summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order #: .
        /// </summary>
        public static string tabprefix {
            get {
                return ResourceManager.GetString("tabprefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra fee.
        /// </summary>
        public static string transportFeeExtraShort {
            get {
                return ResourceManager.GetString("transportFeeExtraShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans fee.
        /// </summary>
        public static string transportFeeShort {
            get {
                return ResourceManager.GetString("transportFeeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string transportfeetotal {
            get {
                return ResourceManager.GetString("transportfeetotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans method:.
        /// </summary>
        public static string transportMethodIDShort {
            get {
                return ResourceManager.GetString("transportMethodIDShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View .
        /// </summary>
        public static string viewlink {
            get {
                return ResourceManager.GetString("viewlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workorder::view.
        /// </summary>
        public static string viewtitle {
            get {
                return ResourceManager.GetString("viewtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekday.
        /// </summary>
        public static string weekday {
            get {
                return ResourceManager.GetString("weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker #.
        /// </summary>
        public static string woidcount {
            get {
                return ResourceManager.GetString("woidcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKER NAME:.
        /// </summary>
        public static string workername {
            get {
                return ResourceManager.GetString("workername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Orders.
        /// </summary>
        public static string workOrders {
            get {
                return ResourceManager.GetString("workOrders", resourceCulture);
            }
        }
    }
}
