//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machete.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkOrders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkOrders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Machete.Web.Resources.WorkOrders", typeof(WorkOrders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I acknowledge that:.
        /// </summary>
        public static string acknowledgement {
            get {
                return ResourceManager.GetString("acknowledgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate order.
        /// </summary>
        public static string activatesubmit {
            get {
                return ResourceManager.GetString("activatesubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active assignment.
        /// </summary>
        public static string activeassignment {
            get {
                return ResourceManager.GetString("activeassignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active order.
        /// </summary>
        public static string activeorder {
            get {
                return ResourceManager.GetString("activeorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment count.
        /// </summary>
        public static string assigncount {
            get {
                return ResourceManager.GetString("assigncount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact person:.
        /// </summary>
        public static string boxcontactname {
            get {
                return ResourceManager.GetString("boxcontactname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on:.
        /// </summary>
        public static string boxdatecreated {
            get {
                return ResourceManager.GetString("boxdatecreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order.
        /// </summary>
        public static string boxlegend {
            get {
                return ResourceManager.GetString("boxlegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string btnActive {
            get {
                return ResourceManager.GetString("btnActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string btnAll {
            get {
                return ResourceManager.GetString("btnAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string btnCancelled {
            get {
                return ResourceManager.GetString("btnCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string btnCompleted {
            get {
                return ResourceManager.GetString("btnCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string btnExpired {
            get {
                return ResourceManager.GetString("btnExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string btnOnline {
            get {
                return ResourceManager.GetString("btnOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string btnPending {
            get {
                return ResourceManager.GetString("btnPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please call 206.956.0779 x3 during &lt;a href=&quot;#&quot; id=&quot;businessHoursModal&quot;&gt;business hours&lt;/a&gt; if you have any questions/issues..
        /// </summary>
        public static string businessHours {
            get {
                return ResourceManager.GetString("businessHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Hours.
        /// </summary>
        public static string businessHoursModal {
            get {
                return ResourceManager.GetString("businessHoursModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        public static string businessName {
            get {
                return ResourceManager.GetString("businessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled assignment.
        /// </summary>
        public static string cancelledassignment {
            get {
                return ResourceManager.GetString("cancelledassignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled order.
        /// </summary>
        public static string cancelledorder {
            get {
                return ResourceManager.GetString("cancelledorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Employer.
        /// </summary>
        public static string changeemployer {
            get {
                return ResourceManager.GetString("changeemployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete active &amp; assigned orders.
        /// </summary>
        public static string completeactiveassigned {
            get {
                return ResourceManager.GetString("completeactiveassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed assignment.
        /// </summary>
        public static string completedassignment {
            get {
                return ResourceManager.GetString("completedassignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed order.
        /// </summary>
        public static string completedorder {
            get {
                return ResourceManager.GetString("completedorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who will be managing the worker(s) at the work site? This may be the person placing the order or another person..
        /// </summary>
        public static string contactName {
            get {
                return ResourceManager.GetString("contactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name (Work Site).
        /// </summary>
        public static string contactNameWorkSite {
            get {
                return ResourceManager.GetString("contactNameWorkSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy employer info.
        /// </summary>
        public static string copyemployerinfo {
            get {
                return ResourceManager.GetString("copyemployerinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Work Order.
        /// </summary>
        public static string createlink {
            get {
                return ResourceManager.GetString("createlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create a new work order, you must first select an existing employer record or create a new employer. Click on the menu box (above) to create or select an employer. Alternatively, you can view an existing work order (below) and then view all orders for that employer..
        /// </summary>
        public static string createnolinkmsg {
            get {
                return ResourceManager.GetString("createnolinkmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string createsubmit {
            get {
                return ResourceManager.GetString("createsubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workorder::create.
        /// </summary>
        public static string createtitle {
            get {
                return ResourceManager.GetString("createtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date needed:.
        /// </summary>
        public static string dateneeded {
            get {
                return ResourceManager.GetString("dateneeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this work order? All information will be deleted, forever. If you want to de-activate this work order, cancel from this dialog and uncheck the &apos;active&apos; box on the work order page..
        /// </summary>
        public static string deleteconfirmation {
            get {
                return ResourceManager.GetString("deleteconfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete .
        /// </summary>
        public static string deletelink {
            get {
                return ResourceManager.GetString("deletelink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deletesubmit {
            get {
                return ResourceManager.GetString("deletesubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workorder::delete.
        /// </summary>
        public static string deletetitle {
            get {
                return ResourceManager.GetString("deletetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string disclaimer {
            get {
                return ResourceManager.GetString("disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string editcancel {
            get {
                return ResourceManager.GetString("editcancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit .
        /// </summary>
        public static string editlink {
            get {
                return ResourceManager.GetString("editlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string editsubmit {
            get {
                return ResourceManager.GetString("editsubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workorder::edit.
        /// </summary>
        public static string edittitle {
            get {
                return ResourceManager.GetString("edittitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit work order.
        /// </summary>
        public static string editworkorderlink {
            get {
                return ResourceManager.GetString("editworkorderlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to move this work order? The tab will be saved and closed. To open it, you must go to the Employer list tab and find the new employer containing the work order..
        /// </summary>
        public static string empChgConfirm {
            get {
                return ResourceManager.GetString("empChgConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string empChgConfirmSubmit {
            get {
                return ResourceManager.GetString("empChgConfirmSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a new employer.
        /// </summary>
        public static string empChgConfirmTitle {
            get {
                return ResourceManager.GetString("empChgConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired assignment.
        /// </summary>
        public static string expiredassignment {
            get {
                return ResourceManager.GetString("expiredassignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired order.
        /// </summary>
        public static string expiredorder {
            get {
                return ResourceManager.GetString("expiredorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Flexible).
        /// </summary>
        public static string flexible {
            get {
                return ResourceManager.GetString("flexible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active orders with fulfilled worker assignments for the date you selected..
        /// </summary>
        public static string groupviewerror {
            get {
                return ResourceManager.GetString("groupviewerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to list of work orders.
        /// </summary>
        public static string indexreturnlink {
            get {
                return ResourceManager.GetString("indexreturnlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workorder::index.
        /// </summary>
        public static string indextitle {
            get {
                return ResourceManager.GetString("indextitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a Business?.
        /// </summary>
        public static string isBusiness {
            get {
                return ResourceManager.GetString("isBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Work Orders.
        /// </summary>
        public static string listlink {
            get {
                return ResourceManager.GetString("listlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of ALL work orders.
        /// </summary>
        public static string listlinkall {
            get {
                return ResourceManager.GetString("listlinkall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of positions.
        /// </summary>
        public static string listOfPositions {
            get {
                return ResourceManager.GetString("listOfPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Work Assignments.
        /// </summary>
        public static string listWorkAssignments {
            get {
                return ResourceManager.GetString("listWorkAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google map.
        /// </summary>
        public static string mapbutton {
            get {
                return ResourceManager.GetString("mapbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online source?.
        /// </summary>
        public static string onlineSource {
            get {
                return ResourceManager.GetString("onlineSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Confirmation.
        /// </summary>
        public static string orderConfirmation {
            get {
                return ResourceManager.GetString("orderConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation fees must be paid online to Casa Latina by using this form. You may pay with debit, credit, or PayPal. Your order is not complete until you have paid the transportation fee..
        /// </summary>
        public static string payPalNotice {
            get {
                return ResourceManager.GetString("payPalNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending assignment.
        /// </summary>
        public static string pendingassignment {
            get {
                return ResourceManager.GetString("pendingassignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending order.
        /// </summary>
        public static string pendingorder {
            get {
                return ResourceManager.GetString("pendingorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone (Work Site).
        /// </summary>
        public static string phoneWorkSite {
            get {
                return ResourceManager.GetString("phoneWorkSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paypal payment.
        /// </summary>
        public static string ppFee {
            get {
                return ResourceManager.GetString("ppFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paypal payment ID.
        /// </summary>
        public static string ppPaymentID {
            get {
                return ResourceManager.GetString("ppPaymentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paypal payment state.
        /// </summary>
        public static string ppState {
            get {
                return ResourceManager.GetString("ppState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print active orders.
        /// </summary>
        public static string printactive {
            get {
                return ResourceManager.GetString("printactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print active &amp; assigned orders.
        /// </summary>
        public static string printactiveassigned {
            get {
                return ResourceManager.GetString("printactiveassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print order.
        /// </summary>
        public static string printlink {
            get {
                return ResourceManager.GetString("printlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print work order.
        /// </summary>
        public static string printWorkOrder {
            get {
                return ResourceManager.GetString("printWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (sharp).
        /// </summary>
        public static string sharp {
            get {
                return ResourceManager.GetString("sharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string summary {
            get {
                return ResourceManager.GetString("summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order #: .
        /// </summary>
        public static string tabprefix {
            get {
                return ResourceManager.GetString("tabprefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Needed.
        /// </summary>
        public static string timeNeeded {
            get {
                return ResourceManager.GetString("timeNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transportation fee (paid to Casa Latina Day Worker Center) is:.
        /// </summary>
        public static string transportationFee {
            get {
                return ResourceManager.GetString("transportationFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra fee.
        /// </summary>
        public static string transportFeeExtraShort {
            get {
                return ResourceManager.GetString("transportFeeExtraShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans fee.
        /// </summary>
        public static string transportFeeShort {
            get {
                return ResourceManager.GetString("transportFeeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string transportfeetotal {
            get {
                return ResourceManager.GetString("transportfeetotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans method:.
        /// </summary>
        public static string transportMethodIDShort {
            get {
                return ResourceManager.GetString("transportMethodIDShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View .
        /// </summary>
        public static string viewlink {
            get {
                return ResourceManager.GetString("viewlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workorder::view.
        /// </summary>
        public static string viewtitle {
            get {
                return ResourceManager.GetString("viewtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekday.
        /// </summary>
        public static string weekday {
            get {
                return ResourceManager.GetString("weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Requirements.
        /// </summary>
        public static string weightRequirements {
            get {
                return ResourceManager.GetString("weightRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker #.
        /// </summary>
        public static string woidcount {
            get {
                return ResourceManager.GetString("woidcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Worker(s).
        /// </summary>
        public static string workAssignments {
            get {
                return ResourceManager.GetString("workAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be as detailed as possible in describing the work needed. Providing detailed information allows us to match you with the best available worker. If worker is asked to do something not listed here, he or she reserves the right to refuse service and minimum wages will still be charged..
        /// </summary>
        public static string workDescription {
            get {
                return ResourceManager.GetString("workDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Details.
        /// </summary>
        public static string workDetails {
            get {
                return ResourceManager.GetString("workDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKER NAME:.
        /// </summary>
        public static string workername {
            get {
                return ResourceManager.GetString("workername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers Requested.
        /// </summary>
        public static string workersRequested {
            get {
                return ResourceManager.GetString("workersRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Work Order Number is:.
        /// </summary>
        public static string workOrderNumber {
            get {
                return ResourceManager.GetString("workOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Orders.
        /// </summary>
        public static string workOrders {
            get {
                return ResourceManager.GetString("workOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Request.
        /// </summary>
        public static string workRequest {
            get {
                return ResourceManager.GetString("workRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (1) Work Site.
        /// </summary>
        public static string workSiteAddress1 {
            get {
                return ResourceManager.GetString("workSiteAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the address where the work will be completed. This is the address to which we will send workers..
        /// </summary>
        public static string workSiteAddress1Dialog {
            get {
                return ResourceManager.GetString("workSiteAddress1Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (2) Work Site.
        /// </summary>
        public static string workSiteAddress2 {
            get {
                return ResourceManager.GetString("workSiteAddress2", resourceCulture);
            }
        }
    }
}
