//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machete.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Workers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Workers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Machete.Web.Resources.Workers", typeof(Workers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker.
        /// </summary>
        public static string boxlegend {
            get {
                return ResourceManager.GetString("boxlegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Worker.
        /// </summary>
        public static string createlink {
            get {
                return ResourceManager.GetString("createlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string createsubmit {
            get {
                return ResourceManager.GetString("createsubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to worker::create.
        /// </summary>
        public static string createtitle {
            get {
                return ResourceManager.GetString("createtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this worker? All information will be deleted, forever. If you want to de-activate this Worker, cancel from this dialog and uncheck the &apos;active&apos; box on the worker page..
        /// </summary>
        public static string deleteconfirmation {
            get {
                return ResourceManager.GetString("deleteconfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deletelink {
            get {
                return ResourceManager.GetString("deletelink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deletesubmit {
            get {
                return ResourceManager.GetString("deletesubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to worker::delete.
        /// </summary>
        public static string deletetitle {
            get {
                return ResourceManager.GetString("deletetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string editlink {
            get {
                return ResourceManager.GetString("editlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string editsubmit {
            get {
                return ResourceManager.GetString("editsubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to worker::edit.
        /// </summary>
        public static string edittitle {
            get {
                return ResourceManager.GetString("edittitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Worker.
        /// </summary>
        public static string editworkerlink {
            get {
                return ResourceManager.GetString("editworkerlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to List of Workers.
        /// </summary>
        public static string indexreturnlink {
            get {
                return ResourceManager.GetString("indexreturnlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to worker::index.
        /// </summary>
        public static string indextitle {
            get {
                return ResourceManager.GetString("indextitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List workers.
        /// </summary>
        public static string listlink {
            get {
                return ResourceManager.GetString("listlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image associated with worker.
        /// </summary>
        public static string noimagelabel {
            get {
                return ResourceManager.GetString("noimagelabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print worker.
        /// </summary>
        public static string printlink {
            get {
                return ResourceManager.GetString("printlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Worker.
        /// </summary>
        public static string rateWorker {
            get {
                return ResourceManager.GetString("rateWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload new image:.
        /// </summary>
        public static string uploadnewimage {
            get {
                return ResourceManager.GetString("uploadnewimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string viewlink {
            get {
                return ResourceManager.GetString("viewlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to worker::view.
        /// </summary>
        public static string viewtitle {
            get {
                return ResourceManager.GetString("viewtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker ID#:.
        /// </summary>
        public static string workerDwcCardNum {
            get {
                return ResourceManager.GetString("workerDwcCardNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Name:.
        /// </summary>
        public static string workerName {
            get {
                return ResourceManager.GetString("workerName", resourceCulture);
            }
        }
    }
}
