//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machete.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkAssignments {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkAssignments() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Machete.Web.Resources.WorkAssignments", typeof(WorkAssignments).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work assignment.
        /// </summary>
        public static string boxlegend {
            get {
                return ResourceManager.GetString("boxlegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new work assignment.
        /// </summary>
        public static string createlink {
            get {
                return ResourceManager.GetString("createlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create a new work assignment, you must first select an existing work order record or create a new work order. Click on the menu box (above) to create or select an existing work order. Alternatively, you can view an existing work assignment (below) and then view all assignments for that work order..
        /// </summary>
        public static string createnolinkmsg {
            get {
                return ResourceManager.GetString("createnolinkmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string createsubmit {
            get {
                return ResourceManager.GetString("createsubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workassignment::create.
        /// </summary>
        public static string createtitle {
            get {
                return ResourceManager.GetString("createtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this work assignment? All information will be deleted, forever. If you want to de-activate this work assignment, cancel from this dialog and uncheck the &apos;active&apos; box on the work assignment page..
        /// </summary>
        public static string deleteconfirmation {
            get {
                return ResourceManager.GetString("deleteconfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deletelink {
            get {
                return ResourceManager.GetString("deletelink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deletesubmit {
            get {
                return ResourceManager.GetString("deletesubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workassignment::delete.
        /// </summary>
        public static string deletetitle {
            get {
                return ResourceManager.GetString("deletetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate assignment.
        /// </summary>
        public static string dupsubmit {
            get {
                return ResourceManager.GetString("dupsubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string editlink {
            get {
                return ResourceManager.GetString("editlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string editsubmit {
            get {
                return ResourceManager.GetString("editsubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workassignment::edit.
        /// </summary>
        public static string edittitle {
            get {
                return ResourceManager.GetString("edittitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit work assignment.
        /// </summary>
        public static string editworkorderlink {
            get {
                return ResourceManager.GetString("editworkorderlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to list of work assignments.
        /// </summary>
        public static string indexreturnlink {
            get {
                return ResourceManager.GetString("indexreturnlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workassignment::index.
        /// </summary>
        public static string indextitle {
            get {
                return ResourceManager.GetString("indextitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List work assignments.
        /// </summary>
        public static string listlink {
            get {
                return ResourceManager.GetString("listlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of ALL work assignments.
        /// </summary>
        public static string listlinkall {
            get {
                return ResourceManager.GetString("listlinkall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment #: .
        /// </summary>
        public static string tabprefix {
            get {
                return ResourceManager.GetString("tabprefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string viewlink {
            get {
                return ResourceManager.GetString("viewlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workassignment::view.
        /// </summary>
        public static string viewtitle {
            get {
                return ResourceManager.GetString("viewtitle", resourceCulture);
            }
        }
    }
}
