//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machete.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkOrder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkOrder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Machete.Web.Resources.WorkOrder", typeof(WorkOrder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (Work Site).
        /// </summary>
        public static string addressWorkSite {
            get {
                return ResourceManager.GetString("addressWorkSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A city is required.
        /// </summary>
        public static string cityrequired {
            get {
                return ResourceManager.GetString("cityrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name (Work Site).
        /// </summary>
        public static string contactName {
            get {
                return ResourceManager.GetString("contactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A contact name is required.
        /// </summary>
        public static string contactNamerequired {
            get {
                return ResourceManager.GetString("contactNamerequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Needed.
        /// </summary>
        public static string dateTimeofWork {
            get {
                return ResourceManager.GetString("dateTimeofWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A date and time is required.
        /// </summary>
        public static string dateTimeofWorkrequired {
            get {
                return ResourceManager.GetString("dateTimeofWorkrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A description of the work is required.
        /// </summary>
        public static string descriptionRequired {
            get {
                return ResourceManager.GetString("descriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclosure Agreement Accepted.
        /// </summary>
        public static string disclosureAgreement {
            get {
                return ResourceManager.GetString("disclosureAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Required (at least one worker)?.
        /// </summary>
        public static string englishRequired {
            get {
                return ResourceManager.GetString("englishRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Required Note.
        /// </summary>
        public static string englishRequiredNote {
            get {
                return ResourceManager.GetString("englishRequiredNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English?.
        /// </summary>
        public static string englishShort {
            get {
                return ResourceManager.GetString("englishShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch?.
        /// </summary>
        public static string lunchShort {
            get {
                return ResourceManager.GetString("lunchShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch Supplied?.
        /// </summary>
        public static string lunchSupplied {
            get {
                return ResourceManager.GetString("lunchSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work order notes.
        /// </summary>
        public static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Online?.
        /// </summary>
        public static string onlineSource {
            get {
                return ResourceManager.GetString("onlineSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate (Paper) Order #.
        /// </summary>
        public static string paperOrderNum {
            get {
                return ResourceManager.GetString("paperOrderNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This number must be 5 digits, or blank.
        /// </summary>
        public static string paperOrderNumFormat {
            get {
                return ResourceManager.GetString("paperOrderNumFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        public static string paypal {
            get {
                return ResourceManager.GetString("paypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal Errors.
        /// </summary>
        public static string paypalErrors {
            get {
                return ResourceManager.GetString("paypalErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal Fee.
        /// </summary>
        public static string paypalFee {
            get {
                return ResourceManager.GetString("paypalFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal PayerID.
        /// </summary>
        public static string paypalPayerId {
            get {
                return ResourceManager.GetString("paypalPayerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal Token.
        /// </summary>
        public static string paypalToken {
            get {
                return ResourceManager.GetString("paypalToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Placement?.
        /// </summary>
        public static string permanentPlacement {
            get {
                return ResourceManager.GetString("permanentPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use this form: ###-###-####.
        /// </summary>
        public static string phoneformat {
            get {
                return ResourceManager.GetString("phoneformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A phone number is required.
        /// </summary>
        public static string phonerequired {
            get {
                return ResourceManager.GetString("phonerequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone (Work Site).
        /// </summary>
        public static string phoneWorkSite {
            get {
                return ResourceManager.GetString("phoneWorkSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string requestAdd {
            get {
                return ResourceManager.GetString("requestAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string requestRemove {
            get {
                return ResourceManager.GetString("requestRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Requested Worker.
        /// </summary>
        public static string requestTitle {
            get {
                return ResourceManager.GetString("requestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A state is required.
        /// </summary>
        public static string staterequired {
            get {
                return ResourceManager.GetString("staterequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A status is required (use pending if unsure).
        /// </summary>
        public static string statusrequired {
            get {
                return ResourceManager.GetString("statusrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string statusShort {
            get {
                return ResourceManager.GetString("statusShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than {1} characters.
        /// </summary>
        public static string stringlength {
            get {
                return ResourceManager.GetString("stringlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time Flexible?.
        /// </summary>
        public static string timeFlexible {
            get {
                return ResourceManager.GetString("timeFlexible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation Fee.
        /// </summary>
        public static string transportFee {
            get {
                return ResourceManager.GetString("transportFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Transportation Fee.
        /// </summary>
        public static string transportFeeExtra {
            get {
                return ResourceManager.GetString("transportFeeExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fee is required (can be $0).
        /// </summary>
        public static string transportFeeExtraRequired {
            get {
                return ResourceManager.GetString("transportFeeExtraRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fee is required (can be $0).
        /// </summary>
        public static string transportFeeRequired {
            get {
                return ResourceManager.GetString("transportFeeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation Method.
        /// </summary>
        public static string transportMethodID {
            get {
                return ResourceManager.GetString("transportMethodID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transport method is required.
        /// </summary>
        public static string transportMethodIDrequired {
            get {
                return ResourceManager.GetString("transportMethodIDrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport Provider.
        /// </summary>
        public static string transportProviderID {
            get {
                return ResourceManager.GetString("transportProviderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment #.
        /// </summary>
        public static string transportTransactID {
            get {
                return ResourceManager.GetString("transportTransactID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        public static string transportTransactType {
            get {
                return ResourceManager.GetString("transportTransactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Program Type.
        /// </summary>
        public static string typeOfWorkID {
            get {
                return ResourceManager.GetString("typeOfWorkID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type of work is required.
        /// </summary>
        public static string typeOfWorkIDrequired {
            get {
                return ResourceManager.GetString("typeOfWorkIDrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Count.
        /// </summary>
        public static string workerCount {
            get {
                return ResourceManager.GetString("workerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests for Workers.
        /// </summary>
        public static string workerRequests {
            get {
                return ResourceManager.GetString("workerRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order #:.
        /// </summary>
        public static string workorderID {
            get {
                return ResourceManager.GetString("workorderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (1) (Work Site).
        /// </summary>
        public static string workSiteAddress1 {
            get {
                return ResourceManager.GetString("workSiteAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An address is required.
        /// </summary>
        public static string workSiteAddress1required {
            get {
                return ResourceManager.GetString("workSiteAddress1required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (2) (Work Site).
        /// </summary>
        public static string workSiteAddress2 {
            get {
                return ResourceManager.GetString("workSiteAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipcode.
        /// </summary>
        public static string zipcode {
            get {
                return ResourceManager.GetString("zipcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A zipcode is required.
        /// </summary>
        public static string zipcoderequired {
            get {
                return ResourceManager.GetString("zipcoderequired", resourceCulture);
            }
        }
    }
}
