//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machete.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkerSignins {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkerSignins() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Machete.Web.Resources.WorkerSignins", typeof(WorkerSignins).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string allrecords {
            get {
                return ResourceManager.GetString("allrecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed in.
        /// </summary>
        public static string datesignin {
            get {
                return ResourceManager.GetString("datesignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this signin? .
        /// </summary>
        public static string deleteconfirmation {
            get {
                return ResourceManager.GetString("deleteconfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deletelink {
            get {
                return ResourceManager.GetString("deletelink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deletesubmit {
            get {
                return ResourceManager.GetString("deletesubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workersignin::delete.
        /// </summary>
        public static string deletetitle {
            get {
                return ResourceManager.GetString("deletetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No..
        /// </summary>
        public static string dwccardnum {
            get {
                return ResourceManager.GetString("dwccardnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number must be 5 digits long.
        /// </summary>
        public static string dwccardnumerror {
            get {
                return ResourceManager.GetString("dwccardnumerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan a card or enter the card number.
        /// </summary>
        public static string dwccardnumrequired {
            get {
                return ResourceManager.GetString("dwccardnumrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires.
        /// </summary>
        public static string expirationdate {
            get {
                return ResourceManager.GetString("expirationdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string fullname {
            get {
                return ResourceManager.GetString("fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string indexsubmit {
            get {
                return ResourceManager.GetString("indexsubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workersignin::index.
        /// </summary>
        public static string indextitle {
            get {
                return ResourceManager.GetString("indextitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear this lottery record? The worker will lose their place in the lottery drawing..
        /// </summary>
        public static string lotteryClearConfirmation {
            get {
                return ResourceManager.GetString("lotteryClearConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string lotteryClearLink {
            get {
                return ResourceManager.GetString("lotteryClearLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string lotteryClearSubmit {
            get {
                return ResourceManager.GetString("lotteryClearSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Lottery Record.
        /// </summary>
        public static string lotteryClearTitle {
            get {
                return ResourceManager.GetString("lotteryClearTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member expiration.
        /// </summary>
        public static string memberexpiration {
            get {
                return ResourceManager.GetString("memberexpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEMBERSHIP EXPIRED!.
        /// </summary>
        public static string membershipexpiredmessage {
            get {
                return ResourceManager.GetString("membershipexpiredmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image available.
        /// </summary>
        public static string noimage {
            get {
                return ResourceManager.GetString("noimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This member is marked as either sanctioned or expelled. Return their ID card to the person and instruct them to speak with a dispatcher. They are not eligible for work at this time..
        /// </summary>
        public static string redmessage {
            get {
                return ResourceManager.GetString("redmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP! SANCTIONED OR EXPELLED WORKER!.
        /// </summary>
        public static string redmessagetitle {
            get {
                return ResourceManager.GetString("redmessagetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member ID number entered does not exist in Machete and cannot be recorded. The member number must exist before checking members into Machete..
        /// </summary>
        public static string unknownmessage {
            get {
                return ResourceManager.GetString("unknownmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP! UNKNOWN MEMBER NUMBER! SIGN-IN NOT RECORDED!.
        /// </summary>
        public static string unknownmessagetitle {
            get {
                return ResourceManager.GetString("unknownmessagetitle", resourceCulture);
            }
        }
    }
}
