//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machete.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkAssignment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkAssignment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Machete.Web.Resources.WorkAssignment", typeof(WorkAssignment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active?.
        /// </summary>
        public static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Notes.
        /// </summary>
        public static string additionalNotes {
            get {
                return ResourceManager.GetString("additionalNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attitude.
        /// </summary>
        public static string attitude {
            get {
                return ResourceManager.GetString("attitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string comments {
            get {
                return ResourceManager.GetString("comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of days is required.
        /// </summary>
        public static string daysrequired {
            get {
                return ResourceManager.GetString("daysrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this dispatch assignment?.
        /// </summary>
        public static string deleteassignedconfirm {
            get {
                return ResourceManager.GetString("deleteassignedconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete dispatch record.
        /// </summary>
        public static string deleteassignedtitle {
            get {
                return ResourceManager.GetString("deleteassignedtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatch information.
        /// </summary>
        public static string dispatchinfo {
            get {
                return ResourceManager.GetString("dispatchinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required English Level.
        /// </summary>
        public static string englishLevelID {
            get {
                return ResourceManager.GetString("englishLevelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eng #.
        /// </summary>
        public static string englishlevelshort {
            get {
                return ResourceManager.GetString("englishlevelshort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability to follow directions.
        /// </summary>
        public static string followDirections {
            get {
                return ResourceManager.GetString("followDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly Wage.
        /// </summary>
        public static string hourlyWage {
            get {
                return ResourceManager.GetString("hourlyWage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An hourly wage is required.
        /// </summary>
        public static string hourlyWagerequired {
            get {
                return ResourceManager.GetString("hourlyWagerequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour Range.
        /// </summary>
        public static string hourRange {
            get {
                return ResourceManager.GetString("hourRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours of Work.
        /// </summary>
        public static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Chambita.
        /// </summary>
        public static string hoursChambita {
            get {
                return ResourceManager.GetString("hoursChambita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Positions in work order.
        /// </summary>
        public static string printListOfPositions {
            get {
                return ResourceManager.GetString("printListOfPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Quality.
        /// </summary>
        public static string qualityOfWork {
            get {
                return ResourceManager.GetString("qualityOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliability.
        /// </summary>
        public static string reliability {
            get {
                return ResourceManager.GetString("reliability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        public static string skillID {
            get {
                return ResourceManager.GetString("skillID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A skill is required (use general labor if none was specificed).
        /// </summary>
        public static string skillIDRequired {
            get {
                return ResourceManager.GetString("skillIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than {1} characters.
        /// </summary>
        public static string stringlength {
            get {
                return ResourceManager.GetString("stringlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surcharge.
        /// </summary>
        public static string surcharge {
            get {
                return ResourceManager.GetString("surcharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport program (if used).
        /// </summary>
        public static string transportProgram {
            get {
                return ResourceManager.GetString("transportProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work ID.
        /// </summary>
        public static string WAID {
            get {
                return ResourceManager.GetString("WAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Heavy Lifting.
        /// </summary>
        public static string weightLifted {
            get {
                return ResourceManager.GetString("weightLifted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information from work order.
        /// </summary>
        public static string WOdescription {
            get {
                return ResourceManager.GetString("WOdescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Rating.
        /// </summary>
        public static string workerRating {
            get {
                return ResourceManager.GetString("workerRating", resourceCulture);
            }
        }
    }
}
