//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machete.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Worker {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Worker() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Machete.Web.Resources.Worker", typeof(Worker).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Worker.
        /// </summary>
        public static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Born Children.
        /// </summary>
        public static string americanBornChildren {
            get {
                return ResourceManager.GetString("americanBornChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car insurance.
        /// </summary>
        public static string carinsurance {
            get {
                return ResourceManager.GetString("carinsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of origin.
        /// </summary>
        public static string countryoforiginID {
            get {
                return ResourceManager.GetString("countryoforiginID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string datecreated {
            get {
                return ResourceManager.GetString("datecreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date in This City.
        /// </summary>
        public static string dateinseattle {
            get {
                return ResourceManager.GetString("dateinseattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date in the USA.
        /// </summary>
        public static string dateinUSA {
            get {
                return ResourceManager.GetString("dateinUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string dateOfBirth {
            get {
                return ResourceManager.GetString("dateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Membership.
        /// </summary>
        public static string dateOfMembership {
            get {
                return ResourceManager.GetString("dateOfMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disability description.
        /// </summary>
        public static string disabilitydesc {
            get {
                return ResourceManager.GetString("disabilitydesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has a U.S. driver&apos;s license?.
        /// </summary>
        public static string driverslicense {
            get {
                return ResourceManager.GetString("driverslicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership #.
        /// </summary>
        public static string dwccardnum {
            get {
                return ResourceManager.GetString("dwccardnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number must be 5 digits long.
        /// </summary>
        public static string dwccardnumerror {
            get {
                return ResourceManager.GetString("dwccardnumerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Level.
        /// </summary>
        public static string educationLevel {
            get {
                return ResourceManager.GetString("educationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency contact in country of origin.
        /// </summary>
        public static string emcontoriginname {
            get {
                return ResourceManager.GetString("emcontoriginname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency contact in country of origin&apos;s phone #.
        /// </summary>
        public static string emcontoriginphone {
            get {
                return ResourceManager.GetString("emcontoriginphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency contact in country of origin&apos;s relation to worker.
        /// </summary>
        public static string emcontoriginrelation {
            get {
                return ResourceManager.GetString("emcontoriginrelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency contact in the USA.
        /// </summary>
        public static string emcontUSAname {
            get {
                return ResourceManager.GetString("emcontUSAname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency contact&apos;s phone #.
        /// </summary>
        public static string emcontUSAphone {
            get {
                return ResourceManager.GetString("emcontUSAphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency contact&apos;s relation to worker.
        /// </summary>
        public static string emcontUSArelation {
            get {
                return ResourceManager.GetString("emcontUSArelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English level.
        /// </summary>
        public static string englishlevelID {
            get {
                return ResourceManager.GetString("englishlevelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm Labor Characteristics.
        /// </summary>
        public static string farmLaborCharacteristics {
            get {
                return ResourceManager.GetString("farmLaborCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Insurance?.
        /// </summary>
        public static string healthInsurance {
            get {
                return ResourceManager.GetString("healthInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Insurance Expiration.
        /// </summary>
        public static string healthInsuranceDate {
            get {
                return ResourceManager.GetString("healthInsuranceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homeless.
        /// </summary>
        public static string homeless {
            get {
                return ResourceManager.GetString("homeless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housing Type.
        /// </summary>
        public static string housingType {
            get {
                return ResourceManager.GetString("housingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immigrant refugee?.
        /// </summary>
        public static string immigrantrefugee {
            get {
                return ResourceManager.GetString("immigrantrefugee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income level.
        /// </summary>
        public static string incomeID {
            get {
                return ResourceManager.GetString("incomeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Source.
        /// </summary>
        public static string incomeSourceID {
            get {
                return ResourceManager.GetString("incomeSourceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car insurance expiration date.
        /// </summary>
        public static string insuranceexpiration {
            get {
                return ResourceManager.GetString("insuranceexpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro To Center.
        /// </summary>
        public static string introToCenter {
            get {
                return ResourceManager.GetString("introToCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Payment Amount.
        /// </summary>
        public static string lastPaymentAmount {
            get {
                return ResourceManager.GetString("lastPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Payment Date.
        /// </summary>
        public static string lastPaymentDate {
            get {
                return ResourceManager.GetString("lastPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LGBTQ?.
        /// </summary>
        public static string lgbtq {
            get {
                return ResourceManager.GetString("lgbtq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver&apos;s license expiration date.
        /// </summary>
        public static string licenseexpirationdate {
            get {
                return ResourceManager.GetString("licenseexpirationdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lives alone.
        /// </summary>
        public static string livealone {
            get {
                return ResourceManager.GetString("livealone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lives with children.
        /// </summary>
        public static string livewithchildren {
            get {
                return ResourceManager.GetString("livewithchildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lives WIth Description.
        /// </summary>
        public static string liveWithDescription {
            get {
                return ResourceManager.GetString("liveWithDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lives With Spouse.
        /// </summary>
        public static string liveWithSpouse {
            get {
                return ResourceManager.GetString("liveWithSpouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Marital Status.
        /// </summary>
        public static string maritalstatus {
            get {
                return ResourceManager.GetString("maritalstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        public static string memberexpirationdate {
            get {
                return ResourceManager.GetString("memberexpirationdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactivation date.
        /// </summary>
        public static string memberReactivateDate {
            get {
                return ResourceManager.GetString("memberReactivateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member status.
        /// </summary>
        public static string memberStatus {
            get {
                return ResourceManager.GetString("memberStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighborhood.
        /// </summary>
        public static string neighborhoodID {
            get {
                return ResourceManager.GetString("neighborhoodID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Children Under 18.
        /// </summary>
        public static string numChildrenUnder18 {
            get {
                return ResourceManager.GetString("numChildrenUnder18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Children in USA.
        /// </summary>
        public static string numofchildren {
            get {
                return ResourceManager.GetString("numofchildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children must be between 0 and 20.
        /// </summary>
        public static string numofchildrenRxError {
            get {
                return ResourceManager.GetString("numofchildrenRxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own Tools?.
        /// </summary>
        public static string ownTools {
            get {
                return ResourceManager.GetString("ownTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race / Ethnicity.
        /// </summary>
        public static string raceID {
            get {
                return ResourceManager.GetString("raceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Race.
        /// </summary>
        public static string raceother {
            get {
                return ResourceManager.GetString("raceother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent arrival to the USA?.
        /// </summary>
        public static string recentarrival {
            get {
                return ResourceManager.GetString("recentarrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill (1).
        /// </summary>
        public static string skill1 {
            get {
                return ResourceManager.GetString("skill1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill (2).
        /// </summary>
        public static string skill2 {
            get {
                return ResourceManager.GetString("skill2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill (3).
        /// </summary>
        public static string skill3 {
            get {
                return ResourceManager.GetString("skill3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than {1} characters.
        /// </summary>
        public static string stringlength {
            get {
                return ResourceManager.GetString("stringlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Type.
        /// </summary>
        public static string typeOfWorkID {
            get {
                return ResourceManager.GetString("typeOfWorkID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Veteran.
        /// </summary>
        public static string usVeteran {
            get {
                return ResourceManager.GetString("usVeteran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type.
        /// </summary>
        public static string vehicleTypeID {
            get {
                return ResourceManager.GetString("vehicleTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wage Theft Recovery Amount.
        /// </summary>
        public static string wageTheftRecoveryAmount {
            get {
                return ResourceManager.GetString("wageTheftRecoveryAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wage Theft Victim.
        /// </summary>
        public static string wageTheftVictim {
            get {
                return ResourceManager.GetString("wageTheftVictim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string weight {
            get {
                return ResourceManager.GetString("weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Rating.
        /// </summary>
        public static string workerRating {
            get {
                return ResourceManager.GetString("workerRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Rating Comments.
        /// </summary>
        public static string workerRatingComments {
            get {
                return ResourceManager.GetString("workerRatingComments", resourceCulture);
            }
        }
    }
}
