name: Publish angular sdk to npm

on:
  workflow_dispatch:
    branches: [ master ]
  workflow_run:
    workflows: ["Build and publish docker image"]
    branches: [ master ]
    types:
      - completed

jobs:
  publish-angular-sdk:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dotnet tools
      run: dotnet tool restore
    - name: Restore dependencies
      run:  dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Remove version prefix from swagger.json
      run:  sed -i 's/\"v1\",/\"1\"/g' swagger.json

    - name: Generate openapi angular client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: typescript-angular
        openapi-file: swagger.json
        command-args: --additional-properties=withInterfaces=true,ngVersion=12,npmVersion=1.15.${{ github.run_number }},npmName=machete-client

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Add npm secrets
    # https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow
      run: touch ~/.npmrc && echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/.npmrc

    - name: Publish api client sdk NPM 📦
      run: cd typescript-angular-client && npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
