name: Build and publish docker image

on:
  workflow_dispatch:
    branches: [ master ]
  workflow_run:
    workflows: ["Build and test dotnet core"]
    branches: [ master ]
    types:
      - completed    

jobs:
  build_angular:
    name: Build for production and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out Machete
        uses: actions/checkout@v2
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master        
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: ./github_install_build_UI.sh    
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run:  dotnet restore
      - name: Build dotnet
        run: dotnet build --no-restore
      - name: Publish dotnet to disk
        run: cd Machete.Web && dotnet publish -o published && cd ..

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker container
        run: docker build . -t ndlonmachete/debian:1.15.${{ github.run_number }}
      - name: Push to Docker Hub
        run: docker push ndlonmachete/debian:1.15.${{ github.run_number }}      