name: Build and publish docker image

on:
  workflow_dispatch:
    branches: [ master ]
  workflow_run:
    workflows: ["Build and test dotnet core"]
    branches: [ master ]
    types:
      - completed

jobs:
  build:
    name: Build for production and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out Machete
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker container
        run: docker build . -t ndlonmachete/debian:latest -t ndlonmachete/debian:1.15.${{ github.run_number }} --build-arg machete_version=1.15.${{ github.run_number }}
      - name: Push versioned container
        run: docker push ndlonmachete/debian:1.15.${{ github.run_number }}
      - name: Push latest tag
        run: docker push ndlonmachete/debian:latest