name: Build and test dotnet core

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master, feature/*  ]

jobs:
  build:

    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/guides/about-service-containers
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: passw0rD!
        ports:
          - 1433:1433
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run:  dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
    # skipping reports tests because of 'first-run' issues we dont want to deal with
      run: dotnet test Machete.Test --no-build --verbosity normal --filter '(TestCategory!=Area-Reports)'
