name: Build and test dotnet core

on:
  workflow_dispatch:
    branches: [ master, feature/* ]
  workflow_run:
    workflows: ["Build and publish api client sdk NPM 📦"]
    branches: [ master, feature/* ]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/guides/about-service-containers
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: openapi-spec
    - name: Generate openapi angular client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: typescript-angular
        openapi-file: swagger/v1/swagger.json
        command-args: "withInterfaces=true,ngVersion=12,npmName=machete-client"
    - name: Publish api client sdk NPM 📦
      run: cd typescript-angular-client && npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
